
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import java.io.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author root
 */
public class Autenticacao extends javax.swing.JFrame {

    /**
     * Creates new form Autenticacao
     */
    public Autenticacao() {
        initComponents();
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        //dataehora();
        new Thread(){      //CODE do RELOGIO, chamada da funcao dataehora
            @Override
            public void run (){
                for (;;){
                    dataehora();
                    try {
                        sleep(1000);
                    }catch(InterruptedException ie){
                        ie.printStackTrace();
                    }
                }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Autenticação");
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 750, 450));
        setMaximumSize(new java.awt.Dimension(750, 450));
        setPreferredSize(new java.awt.Dimension(750, 450));
        getContentPane().setLayout(null);

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(480, 180, 90, 33);

        jButton2.setText("Enviar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(480, 340, 90, 33);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/light-orange.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(600, 600));
        jLabel2.setMinimumSize(new java.awt.Dimension(600, 600));
        jLabel2.setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 570, 390);

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Crie seu Usuário e Senha:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(308, 20, 200, 21);

        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 27, 255));
        jLabel3.setText("Entre com seu usuário e senha:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(310, 230, 260, 21);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(384, 60, 190, 31);

        jLabel4.setText("Usuário:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 60, 60, 30);

        jLabel5.setText("Senha:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(330, 105, 44, 21);

        jLabel6.setText("Novamente a Senha:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(248, 141, 140, 30);

        jLabel7.setText("Usuário:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(318, 270, 60, 21);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(390, 260, 180, 31);

        jLabel8.setText("Senha:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(320, 310, 44, 21);

        jLabel9.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jLabel9.setText("Welcome !");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 43, 130, 60);

        jLabel10.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel10.setText("Bem Vindo !");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 93, 190, 60);

        jLabel11.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(128, 199, 209));
        jLabel11.setText("<html><body><a href=\"http://github.com/rodcaseribe/\">Developer: Rodcaseribe</a></body></html>");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 370, 200, 20);

        jLabel12.setFont(new java.awt.Font("Cantarell", 0, 10)); // NOI18N
        jLabel12.setText("<html><body><div align=\"left\">*<u>Dica</u>: Escolha senhas seguras.<br>Use caracteres especiais<br>e senha maior que 10 caracteres.</div></body></html>");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(580, 60, 250, 160);

        jLabel13.setFont(new java.awt.Font("Cantarell", 0, 10)); // NOI18N
        jLabel13.setText("<htmL><head><body>*Sua senha é de carater pessoal<br>e intrasferível</body></head></html>");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(580, 270, 145, 60);

        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(20, 291, 120, 30);

        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(20, 330, 130, 21);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(390, 100, 180, 31);
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(390, 140, 180, 31);
        getContentPane().add(jPasswordField3);
        jPasswordField3.setBounds(390, 300, 180, 31);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(130, 260, 130, 31);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(124, 300, 130, 31);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    // TODO add your handling code here:
        try{    
        //String arquivao = JOptionPane.showInputDialog("Digite a senha:");
        BufferedReader arq2 = new BufferedReader(new FileReader("senhasoi2.txt"));
        jTextField2.setText(arq2.readLine());
        jTextField3.setText(arq2.readLine());
        //jTextField1.setVisible(false);
        
        
        arq2.close();
        }
    catch(Exception erro){
    JOptionPane.showMessageDialog(null,"Não foi possível abrir o arquivo!"+erro.getMessage());
        }
        String val1,val2,val3,val4;
        val1= jTextField2.getText();
        val2= jTextField3.getText();
        val3= jTextField4.getText();
        val4= jPasswordField3.getText();
        if((val1).equals(val3) & (val2).equals(val4)){
            JOptionPane.showMessageDialog(null,"Senha válida");
        }
        else{
            JOptionPane.showMessageDialog(null,"Senha inválida");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String senha1,senha2;
        senha1= jPasswordField1.getText();
        senha2= jPasswordField2.getText();
        if (senha1.equals(senha2))
        {
            try{    
        PrintWriter arq2 = new PrintWriter("senhasoi2.txt");
        arq2.println(jTextField1.getText());
        arq2.println(jPasswordField1.getText());
        //arq2.println(jPasswordField2.getText());
        arq2.close();
        JOptionPane.showMessageDialog(null,"Senha Correta, Cadastro efetuado com sucesso");
            }
        catch(Exception erro){
        JOptionPane.showMessageDialog(null,"Não foi possível gravar no arquivo!, Dica: chmod 777");
        }  
        }
           else{
            JOptionPane.showMessageDialog(null,"Campos de senha não se confirmam, Tente novamente!");
        }

    }//GEN-LAST:event_jButton1ActionPerformed
 
        
    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
        /*Locale locale = new Locale("pt","BR");
GregorianCalendar calendar = new GregorianCalendar();
SimpleDateFormat formatador = new SimpleDateFormat("dd' de 'MMMMM' de 'yyyy' - 'HH':'mm'h'",locale);
jTextField6.setText(formatador.format(calendar.getInstance().getTime()));*/
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     //* @param args the command line arguments
     */
    public void dataehora(){         //FUNCAO DO RELOGIO
        Calendar cal = new GregorianCalendar();
        int dia =cal.get(Calendar.DAY_OF_MONTH);
        int mes = cal.get(Calendar.MONTH);
        int ano = cal.get(Calendar.YEAR);
        int hora = cal.get(Calendar.HOUR);
        int minuto = cal.get(Calendar.MINUTE);
        int segundo = cal.get(Calendar.SECOND);
        
        jLabel14.setText("Data: "+dia+"/"+(mes+1)+"/"+ano);
        jLabel15.setText("Horário: "+hora+":"+minuto+":"+segundo);
    
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Autenticacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Autenticacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Autenticacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Autenticacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Autenticacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
